# Datatype or Shapes

In [1]:
import numpy as np
array1 = np.array([[1,8,5,3,7,4],[5,8,3,7,1,6]])
print(array1)
print(type(array1))

[[1 8 5 3 7 4]
 [5 8 3 7 1 6]]
<class 'numpy.ndarray'>


In [2]:
array1.shape

(2, 6)

In [3]:
array1.dtype

dtype('int32')

In [4]:
# when get help .typr in google " numpy docomentation", "numpy atribute"

In [5]:
arr2 = np.array([0.5,5,3,7,9,5,1.4])
print(arr2)

[0.5 5.  3.  7.  9.  5.  1.4]


In [6]:
arr2.dtype

dtype('float64')

In [7]:
arr3 = np.array([0.5,5,3,7,9,5,1.4], dtype='int32')
print(arr3)

[0 5 3 7 9 5 1]


In [8]:
arr3.dtype

dtype('int32')

# Blank garage

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(6).dtype

dtype('float64')

In [13]:
# khub choto data loss na hobar jonno float data type prefer kore

# Empty

In [14]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# dekhte zeros((4,6)) er moton lagleo smae noy, empty koele just show koray 0 but value onno kisu o hote parei,
# kono ekta 0 memory location allocate kore.
# zeros((4,6)) sob value gulo keo 0 hote badho kore

# Calculations

In [16]:
array1

array([[1, 8, 5, 3, 7, 4],
       [5, 8, 3, 7, 1, 6]])

In [17]:
# not matrix multiplication . it is a elements wise multiplecatioin

In [18]:
array1*array1

array([[ 1, 64, 25,  9, 49, 16],
       [25, 64,  9, 49,  1, 36]])

In [19]:
array1+array1

array([[ 2, 16, 10,  6, 14,  8],
       [10, 16,  6, 14,  2, 12]])

In [20]:
array1**array1

array([[       1, 16777216,     3125,       27,   823543,      256],
       [    3125, 16777216,       27,   823543,        1,    46656]])

In [21]:
array1/array1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
12.0**12

8916100448256.0

In [23]:
np.array([12.0**12])

array([8.91610045e+12])

In [24]:
np.array([12.0**12], dtype='int32')  # syntex hisabe value thik noy tai error

OverflowError: Python int too large to convert to C long

## Slicing

In [25]:
array1

array([[1, 8, 5, 3, 7, 4],
       [5, 8, 3, 7, 1, 6]])

In [26]:
array(4:6)

SyntaxError: invalid syntax (3509829551.py, line 1)

In [27]:
array5 = np.array([5,8,3,6,7,19,4])

In [28]:
array5[3:6]

array([ 6,  7, 19])

In [29]:
new = array5[3:6]

In [30]:
new

array([ 6,  7, 19])

In [31]:
new[0]= 75

In [32]:
array5

array([ 5,  8,  3, 75,  7, 19,  4])

In [33]:
# er reason ta khub e simple new arraay ta chilo array 5 er vitor , taai new2w 0 change korate array 5 er middle a 5 adda holo
# memory location "new" array er and array5 er [6,7,19] same memory location a ache tai emon hosche 

In [34]:
# Same 

In [35]:
array6 = np.array([5,8,3,6,7,19,4])

In [36]:
new2 = array6[3:6].copy()

In [37]:
new2

array([ 6,  7, 19])

In [38]:
new2[0]= 70

In [39]:
array6

array([ 5,  8,  3,  6,  7, 19,  4])

In [40]:
# .copy()   use korar jonno memory location chage hoye ggeche tai ager tar moto holo na

In [41]:
new2

array([70,  7, 19])

In [42]:
# sudhu ne2 tai bodleche 

In [43]:
array1

array([[1, 8, 5, 3, 7, 4],
       [5, 8, 3, 7, 1, 6]])

In [44]:
array1[0]

array([1, 8, 5, 3, 7, 4])

In [45]:
array1[0,3]

3