# Numpy arange, Argsort & Other Tips

In [1]:
import numpy as np

# arange

In [2]:
a = np.arange(10)

In [3]:
b = np.arange(1,11)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# argsort

In [6]:
#Example 1
c = np.array([1,2,5,3,4,6,9,7,8,2,56,6,21,56,456,2,6,5,53,3,41,6,84,93])
c.shape

(24,)

In [7]:
c = c.reshape(6,4)
c


array([[  1,   2,   5,   3],
       [  4,   6,   9,   7],
       [  8,   2,  56,   6],
       [ 21,  56, 456,   2],
       [  6,   5,  53,   3],
       [ 41,   6,  84,  93]])

In [8]:
c = c.reshape(4,6)
c

array([[  1,   2,   5,   3,   4,   6],
       [  9,   7,   8,   2,  56,   6],
       [ 21,  56, 456,   2,   6,   5],
       [ 53,   3,  41,   6,  84,  93]])

In [9]:
c = c.reshape(3,8)
c

array([[  1,   2,   5,   3,   4,   6,   9,   7],
       [  8,   2,  56,   6,  21,  56, 456,   2],
       [  6,   5,  53,   3,  41,   6,  84,  93]])

In [10]:
#Example 2

In [11]:
c = np.array([6,9,7,8,2,56,6,21,57,6,6,456,2,6,5,53,3,41,6,84,93])
np.argsort(c) # index wise sorting

array([ 4, 12, 16, 14,  0, 18, 13,  9, 10,  6,  2,  3,  1,  7, 17, 15,  5,
        8, 19, 20, 11], dtype=int64)

In [12]:
np.argmin(c)

4

In [13]:
np.argmax(c)

11

In [14]:
#Example 3

In [15]:
d = np.array([6,9,7,8,2,56,6,21,57,6,6,456,2,6,5,53,3,41,6,84,93,45,33,37])
d = d.reshape(6,4)
#d.shape
d

array([[  6,   9,   7,   8],
       [  2,  56,   6,  21],
       [ 57,   6,   6, 456],
       [  2,   6,   5,  53],
       [  3,  41,   6,  84],
       [ 93,  45,  33,  37]])

In [16]:
np.argsort(d)

array([[0, 2, 3, 1],
       [0, 2, 3, 1],
       [1, 2, 0, 3],
       [0, 2, 1, 3],
       [0, 2, 1, 3],
       [2, 3, 1, 0]], dtype=int64)

In [17]:
np.argsort(d,axis=0)

array([[1, 2, 3, 0],
       [3, 3, 1, 1],
       [4, 0, 2, 5],
       [0, 4, 4, 3],
       [2, 5, 0, 4],
       [5, 1, 5, 2]], dtype=int64)